### PR TITLE
fix(refute_assigns): Correct a typo

### PR DESCRIPTION
**Pull request by StanisLove**
Hello! I faced a mistake while using your library.

### CODE REVIEW

**Comment by StanisLove** [comment]
@boydm, check this out, please)

**Comment by boydm** [comment]
OK! Was super busy this week prepping for Code BEAM V... I'll get on it.

**Comment by boydm** [comment]
Is in master

**Comment by boydm** [comment]
I'll let it sit in master a few days, then push it to hex as 0.8.3

**Pull request merged**
