### PR TITLE
Fix #39

### LINKED ISSUE #39: An array of checkboxes where none are checked isn't shown with `fetch_form`
*Minor bug; I'll try to have a look at it soonish*

Consider the following and note that the `name` of the second and third line ends in `[]`. 

```html
<input name="procedures[0][name]"          type="text"     value="">
<input name="procedures[0][species_ids][]" type="checkbox" value="1">
<input name="procedures[0][species_ids][]" type="checkbox" value="2">
```

That means a value is submitted with something like this:

```elixir
    |> follow_form(%{procedures:                           
                    %{0 => %{name: "procedure #1",
                             species_ids: [1]}
                    }})
```

That works fine. However, I would expect the result for `fetch_form` to look something like this:

```elixir
  inputs: %{
    _csrf_token: "XCgQR0wwBREzPykwC2Y3egtGIhp0HioOegs4xQORPuldT9s6l7O-CvsZ",
    procedures: %{
      "0": %{name: "", 
             species_ids: []}, ...     # <<<<<<
```

However, it looks like this:

```elixir
  inputs: %{
    _csrf_token: "XCgQR0wwBREzPykwC2Y3egtGIhp0HioOegs4xQORPuldT9s6l7O-CvsZ",
    procedures: %{
      "0": %{name: ""}, ...     # <<<<<<
```

### PR DESCRIPTION
**Pull request by marick**

### CODE REVIEW

**Comment by boydm** [comment]
This is now published to hex as v0.8.2

Thank you Brian!

**Comment by marick** [comment]
Thank you for the opportunity to help some people.

**Comment by boydm** [comment]
No. THANK YOU for helping.

Do you have any interested in helping maintain it?

**Comment by marick** [comment]
Sure

**Pull request merged**
