### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by boydm** [comment]
You added the MIT license without asking. I'm not going to use MIT. I will be adding Apache 2.0.

Please remove the license and I'll consider the rest.

**Comment by kianmeng** [comment]
> You added the MIT license without asking. I'm not going to use MIT. I will be adding Apache 2.0.
> 
> Please remove the license and I'll consider the rest.

@boydm I see. Note that original SPDX license id was set to `MIT` in the `mix.exs`, it was assumed this Elixir library was licensed under MIT instead of Apache-2.0 license.

See https://hex.pm/packages/phoenix_integration

image

**Comment by kianmeng** [comment]
@boydm Any updates on this?

**Comment by boydm** [comment]
My thought is: This PR is too big and does too many different things. it isn't just comments. It changes code, comments, reformats the changelog, attempted to add a license without asking what license it should have and probably more...

It would take too much effort to thoroughly review the changes, so I"m not going to merge this. If you want to take parts of it and try again ok. Keep it single subject please, no wholesale changes of code. If it is a comments update, then stick to just comments.

If it is a code change, then please have it fix a specific bug. I'm not going to merge changes, that significantly change code without a logic flaw reason. Early on, ok, but this is getting pretty mature and code change equals risk. There needs to be a reason.

Don't rewrite the changelog. I liked it the way it was. Don't add or change the license. OK to point out it needed one, but that is something I would add. Don't mix multiple subjects in a single PR. That makes it too hard to review and, now that I've had to think about it, means I won't merge it.

Happy to look at smaller, single subject PRs tho...

**Comment by kianmeng** [comment]
@boydm Noted, and thanks for letting me know. :smile:

**Pull request closed without merging**
