### PR TITLE
Allow phoenix_html 3.0 and update phoenix dependencies

### PR DESCRIPTION
**Pull request by hzeus**
Hi 👋 

[Version 3.0.0 of Phoenix.HTML](https://hex.pm/packages/phoenix_html/3.0.0) has been released a couple of days ago, and so was [Version 0.16.0 of Phoenix.LiveView](https://hex.pm/packages/phoenix_live_view/0.16.0) which already depends on the newer version.

I updated the dependencies to allow for version 3.0 as well. The tests were all green, so I hope there are no compatibility issues.

Thanks for your work on the library!

### CODE REVIEW

**Comment by boydm** [comment]
I'm deep in Scenic issues. Will look at this soon

**Comment by kabturek** [comment]
Just want to report that phoenix_html 3.0 works for me with phoenix_integration

**Comment by boydm** [comment]
Nice! I'm finally getting back to this space.

**Comment by boydm** [comment]
Thank you

**Comment by boydm** [comment]
Now pushed to hex as 0.9.2

**Pull request merged**
